import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REPO } from "./util.ts";
import { buildJobs, type JobKind } from "./plan.ts";

// Exports every image's prompt + exact save path to art-src/PROMPTS.md so art
// can be generated by hand in a browser UI (no API tokens used).

const KIND_TITLE: Record<JobKind, string> = {
  reference: "Reference portraits (make these FIRST)",
  character: "Character outfit states",
  item: "Item icons",
  scene: "Chapter background scenes",
};
const ORDER: JobKind[] = ["reference", "character", "item", "scene"];

const aspect = (size: string) =>
  size === "1024x1536"
    ? "portrait (2:3)"
    : size === "1536x1024"
      ? "landscape (3:2)"
      : "square (1:1)";

const jobs = buildJobs();
const books = [...new Set(jobs.map((j) => j.book))];

let md = `# Art generation prompts

Generated by \`npm run artgen:prompts\`. Make the art by hand in any image tool
(ChatGPT, Gemini, etc.), then **save each PNG to the exact path shown** and
refresh the app — images load automatically.

Tips:
- Do the **reference portrait** for each character first, then upload it as a
  reference when generating that character's outfit states so it stays the same
  character.
- Match the aspect ratio noted for each image.
- ✅ = the file already exists · ⬜ = still needed.
`;

for (const book of books) {
  md += `\n## ${book}\n`;
  for (const kind of ORDER) {
    const group = jobs.filter((j) => j.book === book && j.kind === kind);
    if (!group.length) continue;
    md += `\n### ${KIND_TITLE[kind]}\n`;
    for (const job of group) {
      const status = existsSync(job.targetAbs) ? "✅ done" : "⬜ pending";
      md += `\n#### ${job.label} — ${status}\n`;
      md += `- **Save PNG to:** \`${job.targetRel}\`\n`;
      md += `- **Aspect ratio:** ${aspect(job.size)}\n`;
      if (job.referenceNote) md += `- **Reference:** ${job.referenceNote}\n`;
      md += "\n```text\n" + job.prompt + "\n```\n";
    }
  }
}

const out = join(REPO, "art-src", "PROMPTS.md");
writeFileSync(out, md);
const pending = jobs.filter((j) => !existsSync(j.targetAbs)).length;
console.log(
  `[artgen] Wrote ${jobs.length} prompts (${pending} still pending) to art-src/PROMPTS.md`,
);
